#!/bin/sh
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

set -eu

# This downloads and extracts the indicated version alpine-minirootfs into the current directory.

full_version=${1?full_version ex 3.18.5}
version=$(echo "${full_version}" | sed -En "s/^([0-9]+\.[0-9]+)\.[0-9]+$/\1/p")
patch=$(echo "${full_version}" | cut -f3 -d.)

# Normalize arch to what's available
#
# Note: s390x and ppc64le were added for Knative
arch=$(uname -m)
case ${arch} in
  amd64* )
    arch=x86_64
    ;;
  x86_64* )
    arch=x86_64
    ;;
  arm64* )
    arch=aarch64
    ;;
  aarch64* )
    arch=aarch64
    ;;
  s390x* )
    arch=s390x
    ;;
  ppc64le* )
    arch=ppc64le
    ;;
  * )
    >&2 echo "Unsupported arch: ${arch}"
    exit 1;
esac

echo "Extracting alpine-minirootfs v${full_version} for ${arch} architecture"
wget -qO- https://dl-cdn.alpinelinux.org/alpine/v${version}/releases/${arch}/alpine-minirootfs-${version}.${patch}-${arch}.tar.gz| tar xz
