#!/bin/sh -ue

# This script runs the tests of the project.
#
# See [README.md] for an explanation of this and how CI should use it.
echo "Building Docker image..."
build-bin/build

echo "Verifying Docker image..."
# Invoke a binary in gcompat to ensure arch matches
docker run --rm openzipkin/alpine:test -c 'ldd /usr/lib/libz.so.1'
