# yamllint --format github .github/workflows/ci.yml
---
name: Continuous Integration

# Trigger on pushes or pull requests to the master branch, but not doc-only
on:
  push:
    branches: master
    paths-ignore: '**/*.md'
  pull_request:
    branches: master
    paths-ignore: '**/*.md'

jobs:
  build:
    runs-on: ubuntu-20.04  # newest available distribution, aka focal
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # license-maven-plugin needs the full history to generate copyright
          # year range. Ex. 2013-2020. Don't do a shallow clone!
          fetch-depth: 0
      - name: Cache docker
        uses: actions/cache@v1
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{ runner.os }}-docker
      - name: Test
        # We run tests on non-tagged pushes on pull requests targeted at the
        # master branch.
        if: "!startsWith(github.ref, 'refs/tags')"
        run: |
          build-bin/configure_test
          build-bin/test
