name: Continuous Build Docker

# Trigger on pushes or pull requests to the master branch, but not for documentation-only updates.
on:
  push:
    branches: master
    paths-ignore: '**/*.md'
  pull_request:
    branches: master
    paths-ignore: '**/*.md'

jobs:
  build:
    runs-on: ubuntu-20.04 # aka focal, because this is what we use in Travis
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Cache docker
        uses: actions/cache@v1
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{ runner.os }}-docker
      - name: Test
        if: !startsWith(github.ref, 'refs/tags')
        run:
         - build-bin/configure_test
         - build-bin/test
